### ISSUE TITLE
Cannot use throttle or control stick in SF-1, as well as nose gear clipping.

### ISSUE THREAD

**Issue by HomeworkH8** [Sacchan-VRC/SaccFlightAndVehicles#34]
Whenever I go into my world in VRChat, I am unable to use the throttle or control stick, only the dials work correctly. The nose wheel of the plane also clips into the ground. I am using the VRCCC, and I have these issues on Quest and PC. Did I set something up wrong?

**Comment by Sacchan-VRC** [comment]
Did you get the release version?

**Comment by HomeworkH8** [comment]
I just saw it, it works now. Thank you!
