### ISSUE TITLE
I've seen worlds that integrate these, but i wonder if a quest avatar could spawn and use it... 

### ISSUE THREAD

**Issue by ReDJstone** [Sacchan-VRC/SaccFlightAndVehicles#53]
Could a quest compatible avatar spawn and use this?

Even if the avatar has to be incredibly simple to save resources for the plane's model, if there is any way that it can be done, i'd love it.
I've already seen years ago avatars spawning a lot of stuff or playing animations that even mess with other's screens.
I wouldnt be surprised if spawning a plane with so many details and weapons was possible.

I would really, REALLY love to be able to spawn this plane from the map "Test Pilots". I dont know the plane's name, but i wholeheartedly love the thing.
![image](https://github.com/user-attachments/assets/4091cb82-3a5a-4411-aeee-bba4840886bb)
The speed, the handling, pulling 40Gs like it's nobody's business (In VR it feels absolutely incredible),
I dont know if those are parameters that the map imposes to all of the planes in it, or if it's the plane's own parameters that allow it to handle that well. But i love it nonetheless.

I'll try to organize everything i'm thinking about when i think of "how would an avatar like this need to be?":

<details>

<summary>[Click to open] First off: Why do i love this plane from this map specifically?</summary>

> It handles incredibly well. It can pull 40Gs like it's nobody's business, which in VR it looks amazing. And it's incredibly fun to rotate that sharply when you're used to it in VR. 

> The kinds of movements i've done in this plane would probably kill someone in VR that isn't used to them, and they would most definitely kill me instantly in real life. 
> But we don't talk about that. xD

</details>

--------------

<details>

<summary>[Click to open] The main things that i would really need to see in an avatar that can do this are: </summary>

> - The incredible handling that the plane in the photo has. Optionally, the option to customize it's max speed would also be interesting.
> - As many USABLE weapons as possible (No need for them to be VISIBLE, i'll get to this in the next paragraph).
> - The option to have endless ammunition to just f**k around, even in worlds that have no correlation to planes whatsoever.
> - If it is possible, it would be CRUCIAL to implement the interaction with planes present on maps or with other people's spawned planes.

- If the avatar can't implement the plane with these features, i do NOT think making it would be worth the time...

<details>

<summary>[Click to open] What i meant with "No need for them to be VISIBLE".</summary>

> I dont mind the specific plane model used. I love how the one in the photo looks and if it were me and it was possible, i'd use that one. But i would want every weapon possible to be usable, even if the 3D model doesn't have some of them. 

> Just as an example, i think the plane in the photo can only select "Rockets" and "AAM" (Apart from guns and bombs). I've seen other planes with no "Rockets" but instead "Long AAM" and "Short AAM". 

> I would want all three kinds of rockets to be usable, even if the 3D model doesn't visually have some of them. Visually, the rockets the plane may have can pass off as AAMs to 99% of the people. 
> And the other 1% don't stand around the model and inspect it. They just get in and start flying.

</details>

</details>

----------------

<details>

<summary>[Click to open] Some additional ideas for the planes in general, not only for the avatar:</summary>

> The ability to take off vertically like a helicopter and glide as if it was a heli when at low speeds is something that some planes IRL already have. Switching between the "Airplane" and "Heli" modes could be an interesting addition.
> This would also help with the hypothetical avatar's version, because it would make it possible to use the aircraft on smaller maps. Otherwise, spawning a supersonic aircraft in a small map would be a really bad idea. 

(I'll update this with any other ideas that come to mind.)

</details>

------------
I hope this issue has enough detail to answer any other question that could arise from it.
I'm asking all of this in order to make sure if it could be possible. 
I may even try to make it myself, but only if i'm sure that it is 100% possible to make it including everything i stated.
If not, it's not worth the time.

Thanks in advance for reading all this, and for the help.

**Comment by Sacchan-VRC** [comment]
impossible
